// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJYqXI4Hhn3w3ZC3b6YpF19nMq0dw3lpE',
    appId: '1:1042913021422:web:589496ec19d4c329ee52ff',
    messagingSenderId: '1042913021422',
    projectId: 'notification-6f099',
    authDomain: 'notification-6f099.firebaseapp.com',
    storageBucket: 'notification-6f099.appspot.com',
    measurementId: 'G-37P3N09NYH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8x0Z73iDChuftm3JPCvCMOzUei2-2coA',
    appId: '1:1042913021422:android:8680ef8549a284d1ee52ff',
    messagingSenderId: '1042913021422',
    projectId: 'notification-6f099',
    storageBucket: 'notification-6f099.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0xZLu4ApRZmvtfO25AjzUFUnKU80MwtE',
    appId: '1:1042913021422:ios:cc04dfa52ee18ca1ee52ff',
    messagingSenderId: '1042913021422',
    projectId: 'notification-6f099',
    storageBucket: 'notification-6f099.appspot.com',
    iosClientId: '1042913021422-8emun219jq14v66qi1quda10d8dc7m1i.apps.googleusercontent.com',
    iosBundleId: 'com.example.notification',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0xZLu4ApRZmvtfO25AjzUFUnKU80MwtE',
    appId: '1:1042913021422:ios:cc04dfa52ee18ca1ee52ff',
    messagingSenderId: '1042913021422',
    projectId: 'notification-6f099',
    storageBucket: 'notification-6f099.appspot.com',
    iosClientId: '1042913021422-8emun219jq14v66qi1quda10d8dc7m1i.apps.googleusercontent.com',
    iosBundleId: 'com.example.notification',
  );
}
